# -*- coding: utf-8 -*-
"""Labsheet3-pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13J2pSCDg_jlcNUEOG4_pQydYqmX1bz0H
"""



import pandas as pd
s1=pd.Series([-3,-1,1,3,5,'gaurav',7.5])
print(s1)

print(s1[:2])

a=[1,7,2]
myvar=pd.Series(a,index=['x','y','z'])
print(myvar)
print(myvar["y"])

calories={"day1":420,"day2":350,"day3":240}
myvar=pd.Series(calories)
print(myvar)

s1=pd.Series([-3,-1,1,3,5,'gaurav',7.5])
print(s1[2])

s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s['a'])



"""**PANDAS DATA FRAME**"""

data={"calories":[420,380,390],"duration":[50,45,45]}
print(data)

df=pd.DataFrame(data)
print(df)

import pandas as pd
data = {'Name':[]}