# -*- coding: utf-8 -*-
"""Labsheet2-flickerimages.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u6svgG-ts5Gv7TOgF1qyp-rPEDWtlAhq
"""

from google.colab import drive
drive.mount ('/content/drive')

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/data set/BL-Flickr-Images-Book.csv")
print(df.head(5))

import pandas as pd
import numpy as np
from functools import reduce

for col in df.columns:
  print(col)

to_drop=["Edition Statement","Corporate Author","Former owner"]
df.drop(to_drop, inplace=True,axis=1)
print(df.head(5))

for col in df.columns:
  print(col)

df.set_index('Identifier',inplace = True)
print(df.head())

unwanted_char=['[',',','-','.']
def clean_dates(item):
  dop=str(item.loc['Date of Publication'])
  if dop=='nan' or dop[0]=='[':
    return np.NaN
  for character in unwanted_char:
    if character in dop :
      character_index =dop.find(character)
      dop:dop[:character_index]
      return dop
df['Date of Publication'] = df.apply(clean_dates, axis=1)
print(df['Date of Publication'].head(25))

