# -*- coding: utf-8 -*-
"""network_visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n25IU6T400tbCvbl1IaRgrUX0O-QWWfm
"""

import networkx as nx
import matplotlib.pyplot as plt
g=nx.Graph()
g.add_nodes_from([1, 2, 3, 4, 5])
g.add_edges_from([(1, 2), (1, 3), (2, 3), (3, 4), (5, 1)])
pos = nx.spring_layout(g)
nx.draw(g, pos, with_labels=True, node_color='skyblue', node_size=1400, edge_color='black', width=1, font_size=15)
plt.show()